# https://travis-ci.org/django-athm/django-athm/

dist: xenial
language: python

cache: pip

matrix:
  fast_finish: true

  include:
    - { python: "3.7", env: TOXENV=py37-django22 }
    - { python: "3.7", env: TOXENV=py37-django30 }
    - { python: "3.8", env: TOXENV=py37-django22 }
    - { python: "3.8", env: TOXENV=py37-django30 }

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov
